import React from 'react';
import {v4} from "uuid"
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";

const Index = (props) => {

    return (
        <div>
            <Head>
                <title>Liste des recettes</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1 className="text-blue-600 text-center text-5xl mt-5 mb-10 mx-0 md:pl-3 font-[Lobster]">Vos recettes</h1>
            <div className="flex flex-wrap w-full justify-center items-center md:justify-evenly">
                {props.array.map(item => (
                    <div className="flex flex-col" key={v4()}>
                        <Link href={`./listes/${item.name}`}
                              className="list-none text-lg md:text-2xl text-gray-800 text-center mb-8 font-[Prompt]">
                            <Image
                                src={item.img}
                                alt={item.name}
                                width={250}
                                height={250}
                                className="rounded-xl"/>

                            {item.name.charAt(0).toUpperCase() + item.name.slice(1)}
                        </Link>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Index;

export async function getStaticProps() {
    const data = await import('../../assets/data/recettes.json')
    const array = data.recettes;

    return {
        props: {array}
    }
}